# Uses VS Code Rest Client extension
@baseurl = http://localhost:3100/api


### Get Mexico cams
GET {{baseurl}}/cams/mexico HTTP/1.1


### Get all cams
GET {{baseurl}}/cams HTTP/1.1


### Get all cams-all
GET {{baseurl}}/cams-all HTTP/1.1


### Get hidden cams
GET {{baseurl}}/cams/hidden HTTP/1.1


### Get YouTube cams
GET {{baseurl}}/cams/youtube HTTP/1.1


### Get ID from latest cam
GET {{baseurl}}/cams/latestId HTTP/1.1


### Get cam by ID
GET {{baseurl}}/cams/585 HTTP/1.1


### Add Cam
POST {{baseurl}}/cams/add HTTP/1.1
Content-Type: application/json

{
  "data": {
    "title": "My New Title",
    "webcamUrl": "xxx",
    "imageName": "test-554736.jpg",
    "description": "xxx",
    "country": "USA",
    "state": "Hawaii",
    "area": "Kauai",
    "subarea": "Poipu",
    "lat": "22.0552",
    "lng": "-159.5088",
    "topCam": false,
    "mbcHosted": false
  }
}


### Edit Cam
PUT {{baseurl}}/cams/edit/ HTTP/1.1
Content-Type: application/json

{
  "data": {
    "id": 598,
    "title": "My New Title",
    "webcamUrl": "xxx",
    "imageName": "test-554736.jpg",
    "description": "xxx",
    "country": "USA",
    "state": "Hawaii",
    "area": "Kauai",
    "subarea": "Poipu",
    "lat": "22.0552",
    "lng": "-159.5088",
    "topCam": true,
    "mbcHosted": true
  }
}

### Delete Cam
DELETE {{baseurl}}/cams/delete HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "id": 790
    }
}

### Contact Us
POST {{baseurl}}/mail HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "email": "don@westland.net",
  "message": "The Eagle has landed"
}


### Search cams
POST {{baseurl}}/cams/search HTTP/1.1
Content-Type: application/json

{
  "search":
    {
      "term": "santa monica"
    }
}


### Get all Hawaii cams
GET {{baseurl}}/cams/hawaii HTTP/1.1


### Get a webcam page

GET {{baseurl}}/webcam-page?country=USA&state=California&titleSlug=tropical-reef-camera-powered-by-exploreorg HTTP/1.1
